### ISSUE TITLE
Fix MathExpressionSpan/MathExpressionDrawable's sizing

### ISSUE THREAD

**Issue by kzys** [karino2/kotlitex#68]
Currently we hardcode everything there.

**Comment by karino2** [comment]
I try this issue.

**Comment by karino2** [comment]
Who tells our height now?

A. DynamicDrawableSpan tells his size via FontMetrics argument of getSize.

I use text height as our target height as a first implementation.
This would be come via draw argument if we do not change the FontMetrics in getSize.

For math mode, we should use a little tall height, but I postpone this handling later.

**Comment by karino2** [comment]
In text mode, we should use textSize of TextView. There are no way to get these value from span. I'll pass it from outside.

**Comment by karino2** [comment]
Current status is as below.
https://github.com/karino2/kotlitex/tree/fit_size_work

Now we need to know how large render node bounding box is to properly shrink to specified size.
But it's a little difficult to me.
Could you help me? @kzys 

We are setting font size when render text node.
So we must already know the height of font and it's height (that's why we can place sup properly).
But we do not calculate whole bounding box by now because we didn't need it.
I guess we can calculate it just traverse RenderingNode tree and calculate similar things like drawing.
But it's big change and there might be better way.

**Comment by kzys** [comment]
> So we must already know the height of font and it's height (that's why we can place sup properly).

I'm unsure about this part. Isn't it coming from metrics you have calculated beforehand?

Anyway #91 will make TextNode#updateSize correct, and then calculating the whole size shouldn't be difficult.

**Comment by karino2** [comment]
> Isn't it coming from metrics you have calculated beforehand?

I think so. I'm not sure whether all the necessary information is available after expression tree, but I think kotlitex already calculate bounding box somewhere.

I'll implement bounding box calculation almost the same way as rendering using your PR.
I also think that it's better calculate it when calculate x, y in rendering state, but dup rendering code is easier for a first trial.
